### ISSUE TITLE
Add documentation about code ide

### ISSUE THREAD

**Issue by masters3d** [exercism/xtypescript#12]
Code IDE is an excellent cross platform IDE from Microsoft. We should add instructions on how to set it up to work with TS.

**Comment by Winston-Guess** [comment]
Yes please, I'm struggling to set it up T_T.

**Comment by masters3d** [comment]
Have you tried this https://code.visualstudio.com/docs/languages/typescript ? Would you be interested in adding some links to our documentation that were helpful to you?

**Comment by dsudia** [comment]
I use VS Code as my dominant editor for TS so I can add some info.

**Comment by dsudia** [comment]
@masters3d 

Although I think to stay neutral it should probably include info on how to set it up in a few editors, I could probably put something together about setting up VS Code, Atom and Webstorm.

**Comment by dsudia** [comment]
@masters3d 

Made a PR for discussion: https://github.com/exercism/xtypescript/pull/34
