### ISSUE TITLE
Consider consistency for the exercises

### ISSUE THREAD

**Issue by kytrinyx** [exercism/xtypescript#2]
- Is there a style guide for TypeScript?
- Are these styles encouraged or enforced?
- Are there any conventions that we should adopt on this track for the sake of consistency?
- Can we enforce these?
- Is there a linter? Are there many? Should we use one?
- Is there a common convention for filenames? If not, what should our convention be?

Note that this is about the exercises (the test suites and code examples), not people's solutions.

**Comment by masters3d** [comment]
> Is there a style guide for TypeScript?

https://github.com/Microsoft/TypeScript/wiki/Coding-guidelines

> Are these styles encouraged or enforced?

But it is not enforced. I did adopt some of these. Just encouraged.

> Are there any conventions that we should adopt on this track for the sake of consistency?

Yes. 

> Can we enforce these?

Only Warnings are emitted. The user is able to turn them off in the TSLint.json file. 

> Is there a linter? Are there many? Should we use one?

TSLint. I just know of this. ESLint only works for JS. 

> Is there a common convention for filenames? If not, what should our convention be?

The covention I adopted is the same as the JS track. Same as the folder same.
