### ISSUE TITLE
Implement Continuous Integration

### ISSUE THREAD

**Issue by kytrinyx** [exercism/xtypescript#3]
Implement a test suite that can run both locally and on Travis CI, that verifies that the example code passes the test suite for each exercise.

Things to consider:

If some tests are marked as skipped or pending in some way, then CI should remove these annotations so that all the tests run against the example, not just the first test.

If we need to rewrite the files in any way, we should copy the exercise to a tmp directory first, so that we don't accidentally end up committing changes that are just for continuous integration or testing purposes.

We should make it possible to test just one exercise at a time, because testing everything can take a while, and very often people are just working on one exercise and will only need to run the full test suite before committing the change.

**Comment by masters3d** [comment]
Hi @kytrinyx 
Could you add me as a maintainer so I can change the travis settings and accept PRs? 
Thanks!

**Comment by kytrinyx** [comment]
@masters3d absolutely! Done.
